services:
  safeDB:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=safe
    volumes:
      - safeDBdata:/var/lib/postgresql/data
      
  backend:
      build:
        context: ./backend
      ports:
        - '3333:3333'
        - '5555:5555'
      depends_on:
        - safeDB
      environment:
        - DATABASE_URL=postgresql://docker:docker@safeDB:5432/safe
        - NODE_ENV=dev
        - PORT=3333
        - JWT_SECRET=KaiserInc
      volumes:
        - .:/app
        - /app/node_modules

volumes:
  safeDBdata: