FROM node:22

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json ./
RUN pnpm install

COPY . .

RUN chmod +x ./entrypoint.sh

EXPOSE 3333

CMD ["sh", "./entrypoint.sh"]