FROM node:22

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN apt-get update && apt-get install -y bash

WORKDIR /app

COPY package.json ./

COPY . .

RUN chmod +x ./entrypoint.sh

RUN pnpm install

EXPOSE 3333

CMD ["bash", "./entrypoint.sh"]