FROM node:22

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json ./

COPY . .

RUN chmod +x ./entrypoint.sh

RUN pnpm install

EXPOSE 3333

CMD ["sh", "./entrypoint.sh"]